apiVersion: v1
data:
  locustfile.py: |-
    from locust import HttpUser, task

    class StressTest(HttpUser):
        @task
        def stress_test(self):
            self.client.get("/")

kind: ConfigMap
metadata:
  name: locust-scripts