apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-webserver
    service: webserver
  name: my-webserver
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always