apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-webserver
    service: webserver
  name: my-webserver
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always