apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: user-pass
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: user-pass
          key: password