apiVersion: v1
kind: Pod
metadata:
  name: nginx-tls-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-tls-container
    image: nginx
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: nginx-tls
      mountPath: /etc/nginx/tls
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
  - name: nginx-tls
    secret:
      secretName: my-secret-tls
      items:
      - key: tls.crt
        path: certificate.crt
      - key: tls.key
        path: key-private.key