apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: | # substitua este valor pelo conteúdo do seu arquivo config.json codificado em base64
    <YOUR_AccessKeyDockerHubBase64_HERE>