apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    storage: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pv-hostpath
  storageClassName: local-storage