apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    storage: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.22
    path: /mnt/nfs
  storageClassName: local-storage