apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    pvc: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      storage: hostpath