apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
immutable: true # torna o ConfigMap imutável
data:
  nginx.conf: |
    events { }

    http {
      server {
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/nginx/tls/certificate.crt;
        ssl_certificate_key /etc/nginx/tls/key-private.key;

        location / {
          return 200 'Ola Maria Barrosa!\n';
          add_header Content-Type text/plain;
        }
      }
    }
